import jsPDF from "jspdf";

export function generateProtocolPDF(title: string, content: string) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;

    // Header / Branding
    doc.setFillColor(11, 12, 16); // Anthrazit
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(102, 252, 241); // Teal Bright
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("NEURO-CODE", margin, 20);

    doc.setTextColor(197, 198, 199); // Light Grey
    doc.setFontSize(10);
    doc.setFont("courier", "normal");
    doc.text("PROTOCOL CHECKLIST // ARTIFACT GENERATOR", margin, 28);

    // Title
    doc.setTextColor(0, 0, 0); // Black for main text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    const splitTitle = doc.splitTextToSize(title.toUpperCase(), maxLineWidth);
    doc.text(splitTitle, margin, 60);

    let yPos = 60 + (splitTitle.length * 10);

    // Divider
    doc.setDrawColor(69, 162, 158); // Teal Muted
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // Content Processing
    // We assume the content is raw text. We'll split it by lines and look for "headings"
    const lines = content.split("\n");

    doc.setFontSize(11);

    lines.forEach((line) => {
        if (yPos > 270) {
            doc.addPage();
            yPos = 30;
        }

        // Simple heuristic for headings (ALL CAPS or ending with :)
        if (line.match(/^[A-Z\s]+:|Section|Phase/)) {
            doc.setFont("helvetica", "bold");
            doc.setTextColor(31, 40, 51); // Dark Grey
            yPos += 5;
            doc.text(line, margin, yPos);
            yPos += 7;
            doc.setFont("helvetica", "normal");
            doc.setTextColor(60, 60, 60);
        }
        // Heuristic for bullet points
        else if (line.trim().startsWith("-") || line.trim().startsWith("*")) {
            const cleanLine = line.replace(/^[-*]\s*/, "");
            const splitLine = doc.splitTextToSize(`• ${cleanLine}`, maxLineWidth - 5);
            doc.text(splitLine, margin + 5, yPos);
            yPos += (splitLine.length * 6);
        }
        else {
            const splitLine = doc.splitTextToSize(line, maxLineWidth);
            doc.text(splitLine, margin, yPos);
            yPos += (splitLine.length * 6);
        }
    });

    // Footer
    const pageCount = (doc as any).getNumberOfPages ? (doc as any).getNumberOfPages() : (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} | Generated by Neuro-Code Optimizer`, margin, 285);
    }

    doc.save(`${title.replace(/\s+/g, "_").toLowerCase()}_protocol.pdf`);
}
