"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useEffect, useState } from "react";
import { Sparkles, Crown } from "lucide-react";
import { FUTURE_IDEAS, GOD_MODE_PROMPTS } from "./mockData";

interface Idea {
    id: number;
    text?: string;
    title?: string;
    score: number;
    type?: "HOOK" | "EDIT" | "RETENTION";
    viral?: boolean;
}

export default function IdeaStream({ godMode = false }: { godMode?: boolean }) {
    const [ideas, setIdeas] = useState<Idea[]>([]);

    useEffect(() => {
        const interval = setInterval(() => {
            setIdeas(prev => {
                const nextIdeas = [...prev];
                // Choose source based on mode
                const source = godMode ? GOD_MODE_PROMPTS : FUTURE_IDEAS;

                // Randomly pick an idea to add to the top
                const randomIdea = source[Math.floor(Math.random() * source.length)];
                nextIdeas.unshift({ ...randomIdea, id: Date.now() }); // Unique ID
                if (nextIdeas.length > 8) nextIdeas.pop(); // Keep list short
                return nextIdeas;
            });
        }, godMode ? 800 : 2000); // Faster in God Mode

        return () => clearInterval(interval);
    }, [godMode]);

    return (
        <div className="h-full flex flex-col overflow-hidden relative">
            <div className="absolute inset-0 bg-gradient-to-b from-background via-transparent to-background z-10 pointer-events-none" />

            <div className="flex-1 space-y-3 p-4 overflow-hidden">
                <AnimatePresence>
                    {ideas.map((idea) => (
                        <motion.div
                            key={idea.id}
                            initial={{ opacity: 0, y: -20, scale: 0.9 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            exit={{ opacity: 0, y: 20 }}
                            transition={{ duration: 0.5 }}
                            className={`
                                p-3 rounded-lg border backdrop-blur-md relative overflow-hidden group
                                ${godMode
                                    ? "border-yellow-500/40 bg-yellow-900/20"
                                    : (idea.viral ? "border-purple-500/30 bg-purple-500/5" : "border-border/50 bg-card/30")
                                }
                            `}
                        >
                            {/* Glowing Background for Viral/God Items */}
                            {(idea.viral || godMode) && (
                                <div className={`absolute inset-0 blur-xl transition-all ${godMode ? "bg-yellow-500/10 group-hover:bg-yellow-500/30" : "bg-purple-500/10 group-hover:bg-purple-500/20"}`} />
                            )}

                            <div className="flex justify-between items-start relative z-10">
                                <div>
                                    <h4 className={`text-sm font-bold flex items-center gap-2 ${godMode ? "text-yellow-200" : "text-white"}`}>
                                        {godMode ? <Crown className="w-3 h-3 text-yellow-400 animate-pulse" /> : (idea.viral && <Sparkles className="w-3 h-3 text-yellow-400 animate-pulse" />)}
                                        {idea.title || idea.text}
                                    </h4>
                                    <p className="text-[10px] text-muted-foreground mt-1">Generated by {godMode ? "GOD-MODE v1.0" : "Neuro-Core v9.1"}</p>
                                </div>
                                <div className="text-right">
                                    <div className={`text-lg font-bold font-mono ${godMode ? "text-yellow-400" : "text-primary"}`}>{idea.score}%</div>
                                    <div className="text-[9px] uppercase tracking-wider text-muted-foreground">Potency</div>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </AnimatePresence>

                {ideas.length === 0 && (
                    <div className="text-center text-muted-foreground text-xs mt-10 animate-pulse">
                        {godMode ? "AWAITING DIVINE INTERVENTION..." : "SENSORS CALIBRATING..."}
                    </div>
                )}
            </div>
        </div>
    );
}
